### ISSUE TITLE
Runes in the config menu are highly pixelated

### ISSUE THREAD

**Issue by evilgenious448** [DapperMickie/runepouch-loadout-names#1]
The runes in the configuration menu, as well as the text above them is highly pixelated. I know they are already pixelated even at full size due to the art style of OSRS, but this is a bit too jarring on the eyes.
![image](https://github.com/DapperMickie/runepouch-loadout-names/assets/32331499/5b94d78a-400f-43b1-8ae5-385ee4b461c5)

A possible solution would be to scale down the Loadout name text. This not only will help reduce the pixelation of the Runes and numbers, but also will allow for even longer names. 

Thank you :)

**Comment by DapperMickie** [comment]
This is for the name that is shown:
https://github.com/DapperMickie/runepouch-loadout-names/blob/master/src/main/java/com/github/dappermickie/runepouch/loadout/names/RunepouchLoadoutNamesPlugin.java#L270

This is for the x position of the runes (if it's a runepouch with 3 runes):
https://github.com/DapperMickie/runepouch-loadout-names/blob/master/src/main/java/com/github/dappermickie/runepouch/loadout/names/RunepouchLoadoutNamesPlugin.java#L260

This is the logic for changing the width and height for the runes:
https://github.com/DapperMickie/runepouch-loadout-names/blob/master/src/main/java/com/github/dappermickie/runepouch/loadout/names/RunepouchLoadoutNamesPlugin.java#L214

I added a command `::resetrunepouchloadout` that will reset the widget to it's original state, so you can keep keep tweaking it if you're debugging

And if you want even longer names (I think max is currently 40) you have to tweak around with this too:
https://github.com/DapperMickie/runepouch-loadout-names/blob/master/src/main/java/com/github/dappermickie/runepouch/loadout/names/RunepouchLoadoutNamesPlugin.java#L129
